alias: Resume Eufy Alerts
description: Resume Eufy Alerts
triggers:
  - event_type: manual_trigger
    trigger: event
conditions: []
actions:
  - data:
      entity_id:
        - camera.backyard
        - camera.backyard_2
        - camera.barn_door
        - camera.garage
        - camera.garage_2
        - camera.garage_3
        - camera.woodshed
        - camera.skelecam
        - camera.doorbell
      snooze_time: 0
      snooze_chime: false
      snooze_motion: false
      snooze_homebase: false
    action: eufy_security.snooze
mode: single
