alias: Resume Eufy Alerts
description: Resume Eufy Alerts
triggers:
  - event_type: manual_trigger
    trigger: event
conditions: []
actions:
  - data:
      entity_id:
        - camera.1
        - camera.2
        - camera.3
        - camera.4
        - camera.5
        - camera.6
        - camera.7
        - camera.8
        - camera.9     
      snooze_time: 0
      snooze_chime: false
      snooze_motion: false
      snooze_homebase: false
    action: eufy_security.snooze
mode: single
