alias: Snooze Eufy Alerts
description: snooze motion alerts on outside cameras for 60 minutes
triggers:
  - event_type: manual_trigger
    trigger: event
conditions: []
actions:
  - data:
      entity_id:
        - camera.backyard
        - camera.backyard_2
        - camera.barn_door
        - camera.garage
        - camera.garage_2
        - camera.garage_3
        - camera.woodshed
        - camera.skelecam
        - camera.doorbell
      snooze_time: 60
      snooze_chime: false
      snooze_motion: true
      snooze_homebase: false
    action: eufy_security.snooze
mode: single
